INSERT INTO tasks (title, description, status, priority, due_date) VALUES
('Optimize Backend Queries', 'Improve the performance of backend database queries for faster response times.', 'NEW', 'HIGH', '2024-11-14 10:00:00'),
('Frontend UI Redesign', 'Redesign the user interface of the dashboard to improve user experience.', 'NEW', 'MEDIUM', '2024-11-15 14:00:00'),
('API Documentation Update', 'Update the API documentation to include the latest changes in the endpoints.', 'NEW', 'LOW', '2024-11-16 09:00:00'),
('Bug Fix: Payment Gateway', 'Fix the issue causing failed transactions in the payment gateway.', 'NEW', 'HIGH', '2024-11-17 16:00:00'),
('Create New User Role', 'Add a new user role for content moderators in the system.', 'NEW', 'MEDIUM', '2024-11-18 11:00:00'),
('Implement Dark Mode', 'Develop a dark mode option for the application UI.', 'NEW', 'LOW', '2024-11-19 08:00:00'),
('Database Indexing Optimization', 'Optimize the database by adding appropriate indexes to improve query speed.', 'NEW', 'HIGH', '2024-11-20 12:30:00'),
('Email Notification Bug', 'Fix the bug preventing email notifications from being sent to users.', 'NEW', 'MEDIUM', '2024-11-21 17:00:00'),
('Add Search Functionality', 'Implement a search feature for the project dashboard.', 'NEW', 'HIGH', '2024-11-22 13:00:00'),
('Code Review and Refactor', 'Review the current codebase and refactor where necessary for better performance.', 'NEW', 'LOW', '2024-11-23 09:00:00'),
('Setup Continuous Integration', 'Configure CI/CD pipelines for automated testing and deployment.', 'NEW', 'HIGH', '2024-11-24 18:00:00'),
('Add Unit Tests for Backend', 'Increase code coverage by adding unit tests for backend services.', 'NEW', 'MEDIUM', '2024-11-25 11:30:00'),
('SEO Improvements', 'Optimize the website for better search engine visibility.', 'NEW', 'LOW', '2024-11-26 15:00:00'),
('User Feedback Collection', 'Design and implement a user feedback form to collect feedback on new features.', 'NEW', 'HIGH', '2024-11-27 14:00:00'),
('Implement Caching Strategy', 'Add caching to reduce server load and improve response times.', 'NEW', 'MEDIUM', '2024-11-28 10:30:00'),
('Develop Mobile Version', 'Start the development of a mobile version of the web app.', 'NEW', 'HIGH', '2024-11-29 12:00:00'),
('Integrate Social Media Login', 'Add social media login options for Google and Facebook.', 'NEW', 'MEDIUM', '2024-11-30 09:30:00'),
('Fix Responsive Design Issues', 'Resolve UI issues for mobile and tablet devices in the existing layout.', 'NEW', 'LOW', '2024-12-01 16:00:00'),
('Create Admin Dashboard', 'Develop an admin panel for managing user roles and site settings.', 'NEW', 'HIGH', '2024-12-02 14:30:00'),
('Content Upload Feature', 'Allow users to upload and manage content directly from their dashboard.', 'NEW', 'MEDIUM', '2024-12-03 13:00:00'),
('Session Timeout Management', 'Improve session timeout handling to enhance security.', 'NEW', 'HIGH', '2024-12-04 10:00:00'),
('Refactor Authentication Logic', 'Clean up and refactor the authentication process for better scalability.', 'NEW', 'MEDIUM', '2024-12-05 12:00:00'),
('Generate Monthly Reports', 'Implement functionality to generate detailed reports for monthly activities.', 'NEW', 'LOW', '2024-12-06 11:30:00'),
('Database Backup Automation', 'Automate regular backups of the database to prevent data loss.', 'NEW', 'HIGH', '2024-12-07 09:00:00'),
('Add Analytics Dashboard', 'Build an analytics dashboard to show user engagement and site statistics.', 'NEW', 'MEDIUM', '2024-12-08 15:00:00'),
('Push Notifications Setup', 'Set up push notifications for important updates and events.', 'NEW', 'HIGH', '2024-12-09 17:00:00'),
('Update Privacy Policy', 'Revise and update the privacy policy according to new regulations.', 'NEW', 'LOW', '2024-12-10 12:00:00'),
('Create Help Center', 'Develop a help center with FAQs and support resources.', 'NEW', 'MEDIUM', '2024-12-11 13:30:00'),
('Cross-browser Compatibility Fixes', 'Ensure the web app is fully compatible with all major browsers.', 'NEW', 'LOW', '2024-12-12 10:00:00'),
('Database Migration to Cloud', 'Migrate the existing on-prem database to a cloud-based solution.', 'NEW', 'HIGH', '2024-12-13 11:00:00'),
('Optimize Image Loading', 'Reduce image loading times by implementing lazy loading techniques.', 'NEW', 'MEDIUM', '2024-12-14 14:30:00'),
('Multilingual Support', 'Add support for multiple languages on the platform.', 'NEW', 'LOW', '2024-12-15 16:00:00'),
('Improve Security Protocols', 'Update security measures to address potential vulnerabilities.', 'NEW', 'HIGH', '2024-12-16 09:00:00'),
('Bug Fix: User Profile Update', 'Fix the issue preventing users from updating their profiles.', 'NEW', 'MEDIUM', '2024-12-17 11:00:00'),
('Create Referral Program', 'Design a referral program to increase user engagement and growth.', 'NEW', 'HIGH', '2024-12-18 12:00:00'),
('Implement Two-Factor Authentication', 'Add two-factor authentication (2FA) for enhanced security.', 'NEW', 'MEDIUM', '2024-12-19 10:30:00'),
('Content Moderation System', 'Build a content moderation system to filter inappropriate content.', 'NEW', 'LOW', '2024-12-20 15:00:00'),
('Email Templates for Marketing', 'Create reusable email templates for upcoming marketing campaigns.', 'NEW', 'HIGH', '2024-12-21 14:00:00'),
('UI/UX Improvements for Settings Page', 'Revamp the settings page to improve user experience.', 'NEW', 'MEDIUM', '2024-12-22 13:00:00'),
('Payment Integration: Stripe', 'Integrate Stripe for processing payments securely.', 'NEW', 'HIGH', '2024-12-23 11:00:00'),
('Add Calendar Feature', 'Add a calendar feature to track tasks and deadlines.', 'NEW', 'MEDIUM', '2024-12-24 09:30:00'),
('Automated Testing Setup', 'Set up automated tests to ensure the stability of key features.', 'NEW', 'LOW', '2024-12-25 12:30:00'),
('Implement SSO (Single Sign-On)', 'Allow users to log in using single sign-on functionality.', 'NEW', 'HIGH', '2024-12-26 11:00:00'),
('Design New Landing Page', 'Create a new and engaging landing page for marketing purposes.', 'NEW', 'MEDIUM', '2024-12-27 15:00:00'),
('Setup Version Control for Documentation', 'Establish version control for all project-related documentation.', 'NEW', 'LOW', '2024-12-28 16:00:00'),
('Upgrade to Latest Angular Version', 'Update the frontend framework to the latest version of Angular.', 'NEW', 'HIGH', '2024-12-29 17:00:00'),
('Customer Support Chatbot', 'Develop a chatbot to assist customers with common inquiries.', 'NEW', 'MEDIUM', '2024-12-30 09:00:00'),
('Implement Role-based Access Control', 'Add role-based access control (RBAC) to manage user permissions.', 'NEW', 'HIGH', '2024-12-31 10:30:00');
('Plan the Marketing Campaign', 'Develop a comprehensive marketing plan for the upcoming product launch.', 'NEW', 'HIGH', '2024-11-14 09:00:00'),
('Finalize Website Design', 'Review and finalize the design of the new company website with the design team.', 'NEW', 'MEDIUM', '2024-11-14 10:00:00'),
('Prepare Annual Budget Report', 'Gather data and prepare the financial report for the annual company budget review.', 'NEW', 'HIGH', '2024-11-15 12:00:00'),
('Conduct Staff Training on New Software', 'Schedule a training session for employees to learn the new project management software.', 'NEW', 'MEDIUM', '2024-11-15 14:00:00'),
('Update Project Roadmap', 'Revise the current project roadmap with new deadlines and deliverables.', 'NEW', 'LOW', '2024-11-16 10:00:00'),
('Organize Team Building Event', 'Plan a team-building event to boost employee morale and teamwork.', 'NEW', 'MEDIUM', '2024-11-16 11:00:00'),
('Audit IT Security Systems', 'Conduct a thorough audit of the company’s IT security infrastructure.', 'NEW', 'HIGH', '2024-11-17 15:00:00'),
('Review Client Feedback on Product', 'Analyze recent customer feedback and identify areas for product improvement.', 'NEW', 'MEDIUM', '2024-11-17 16:00:00'),
('Launch Customer Satisfaction Survey', 'Prepare and launch a survey to measure customer satisfaction with our services.', 'NEW', 'LOW', '2024-11-18 09:00:00'),
('Develop Marketing Materials', 'Create promotional content, including brochures and flyers, for the new product launch.', 'NEW', 'HIGH', '2024-11-18 11:00:00'),
('Oversee New Employee Onboarding', 'Ensure the smooth onboarding process for new hires, including orientation and training.', 'NEW', 'MEDIUM', '2024-11-19 13:00:00'),
('Research Competitor Products', 'Study competitors’ products and assess their strengths and weaknesses.', 'NEW', 'LOW', '2024-11-19 14:00:00'),
('Setup E-commerce Website', 'Launch the new e-commerce platform and ensure it is fully functional.', 'NEW', 'HIGH', '2024-11-20 08:00:00'),
('Create Content for Social Media Campaign', 'Develop engaging content for the company’s upcoming social media campaigns.', 'NEW', 'MEDIUM', '2024-11-20 10:00:00'),
('Schedule Client Meeting', 'Set up a meeting with a major client to discuss contract renewal and future collaboration.', 'NEW', 'HIGH', '2024-11-21 09:00:00'),
('Analyze Quarterly Sales Data', 'Review and analyze sales data from the last quarter to identify growth areas.', 'NEW', 'LOW', '2024-11-21 11:00:00'),
('Implement New Customer Support System', 'Deploy and configure a new customer support system to improve service quality.', 'NEW', 'HIGH', '2024-11-22 13:00:00'),
('Develop New Feature for Mobile App', 'Work on the development of a new feature for the company’s mobile app.', 'NEW', 'MEDIUM', '2024-11-22 15:00:00'),
('Write Press Release for Product Launch', 'Create a press release announcing the launch of the new product to the media.', 'NEW', 'HIGH', '2024-11-23 09:00:00'),
('Evaluate Employee Performance', 'Conduct performance evaluations for team members and provide feedback.', 'NEW', 'MEDIUM', '2024-11-23 10:00:00'),
('Host Webinar on Industry Trends', 'Organize and host a webinar to discuss emerging trends in the industry.', 'NEW', 'LOW', '2024-11-24 14:00:00'),
('Prepare Investor Presentation', 'Develop a presentation for investors outlining the company’s growth and future prospects.', 'NEW', 'HIGH', '2024-11-24 16:00:00'),
('Upgrade Software to Latest Version', 'Update the company’s core software to the latest stable version for improved performance.', 'NEW', 'MEDIUM', '2024-11-25 09:00:00'),
('Create a Customer Loyalty Program', 'Design a loyalty program to reward and retain long-term customers.', 'NEW', 'LOW', '2024-11-25 11:00:00'),
('Review Marketing Analytics Data', 'Analyze data from current marketing campaigns to assess their effectiveness.', 'NEW', 'MEDIUM', '2024-11-26 13:00:00'),
('Prepare Weekly Project Status Report', 'Summarize the progress of ongoing projects and prepare a status update for the team.', 'NEW', 'LOW', '2024-11-26 14:00:00'),
('Update Employee Handbook', 'Review and update the company’s employee handbook with new policies and procedures.', 'NEW', 'MEDIUM', '2024-11-27 10:00:00'),
('Test Website for Mobile Optimization', 'Perform tests to ensure that the company’s website is fully optimized for mobile devices.', 'NEW', 'HIGH', '2024-11-27 11:00:00'),
('Revise SEO Strategy', 'Update the SEO strategy for the website to improve search engine rankings.', 'NEW', 'HIGH', '2024-11-28 09:00:00'),
('Redesign Company Logo', 'Work with the design team to develop a new logo that represents the company’s branding vision.', 'NEW', 'LOW', '2024-11-28 10:00:00'),
('Prepare for Holiday Season Sales', 'Create a strategy and plan to maximize sales during the upcoming holiday season.', 'NEW', 'HIGH', '2024-11-29 13:00:00'),
('Upgrade Internal Networking System', 'Improve and upgrade the company’s internal network infrastructure for better performance.', 'NEW', 'MEDIUM', '2024-11-29 15:00:00'),
('Launch New Product Feature', 'Prepare marketing and user documentation for the launch of a new feature in the product.', 'NEW', 'HIGH', '2024-11-30 09:00:00'),
('Conduct Market Research for New Product', 'Perform research to assess the market demand and competition for a new product idea.', 'NEW', 'MEDIUM', '2024-11-30 11:00:00'),
('Review User Feedback on New App', 'Gather and analyze user feedback on the newly released app to improve its functionality.', 'NEW', 'LOW', '2024-12-01 10:00:00'),
('Create New Customer Support FAQ', 'Develop a comprehensive FAQ page for the customer support portal to address common questions.', 'NEW', 'MEDIUM', '2024-12-01 13:00:00'),
('Organize Product Photography Session', 'Schedule a session with a professional photographer to create high-quality images for product listings.', 'NEW', 'LOW', '2024-12-02 09:00:00'),
('Evaluate Employee Training Program', 'Assess the effectiveness of the current employee training program and make improvements as needed.', 'NEW', 'MEDIUM', '2024-12-02 10:00:00'),
('Test Backup Systems for Disaster Recovery', 'Perform disaster recovery drills and test backup systems for business continuity.', 'NEW', 'HIGH', '2024-12-03 09:00:00'),
('Revise Company’s Privacy Policy', 'Update the company’s privacy policy to reflect new data protection laws and practices.', 'NEW', 'MEDIUM', '2024-12-03 12:00:00'),
('Develop Business Continuity Plan', 'Create a business continuity plan to ensure operations during emergencies or disruptions.', 'NEW', 'HIGH', '2024-12-04 09:00:00'),
('Set Up New Client Accounts', 'Onboard new clients and set up accounts in the CRM system for ongoing communication.', 'NEW', 'LOW', '2024-12-04 11:00:00'),
('Research Potential Mergers & Acquisitions', 'Investigate possible mergers or acquisitions to expand the company’s market share.', 'NEW', 'HIGH', '2024-12-05 10:00:00'),
('Redesign Marketing Campaign for Winter', 'Plan a new marketing campaign targeting customers during the winter season.', 'NEW', 'MEDIUM', '2024-12-05 13:00:00'),
('Set Up Internal Knowledge Sharing Platform', 'Implement a platform for internal knowledge sharing to facilitate better communication across teams.', 'NEW', 'LOW', '2024-12-06 09:00:00'),
('Build Email Marketing List', 'Create and maintain a list of contacts for email marketing purposes, focusing on customer engagement.', 'NEW', 'MEDIUM', '2024-12-06 10:00:00'),
('Develop a Mobile App for Product Ordering', 'Start the development of a mobile app to allow customers to easily order products on their phones.', 'NEW', 'HIGH', '2024-12-07 09:00:00'),
('Review Employee Compensation Packages', 'Evaluate and make recommendations for adjustments to employee compensation packages.', 'NEW', 'LOW', '2024-12-07 12:00:00'),
('Prepare Digital Marketing Strategy', 'Develop a strategy for digital marketing, focusing on SEO, social media, and paid advertising.', 'NEW', 'HIGH', '2024-12-08 10:00:00'),
('Create New Partnerships with Vendors', 'Identify and reach out to potential vendors for new partnerships that could benefit the company.', 'NEW', 'MEDIUM', '2024-12-08 12:00:00'),
('Host a Virtual Product Launch Event', 'Organize and host a virtual event to launch the new product, with live demonstrations and customer interactions.', 'NEW', 'HIGH', '2024-12-09 14:00:00'),
('Monitor Website Traffic Analytics', 'Track and analyze website traffic to identify patterns and opportunities for growth.', 'NEW', 'LOW', '2024-12-09 15:00:00'),
('Write Case Studies for New Clients', 'Prepare case studies highlighting successful projects with new clients for marketing purposes.', 'NEW', 'MEDIUM', '2024-12-10 09:00:00');
